# First Deep learning project

In [1]:
#https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

How to load data

How to define a neural network in Keras

How to compile a Keras model using the efficient numerical backend

How to train a model on data

How to evaluate a model on data

How to make predictions with the model

In [2]:
# first neural network with keras tutorial
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# binary classficiation

In [4]:
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
data = loadtxt(path, delimiter = ',')

In [5]:
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [6]:
data.shape

(768, 9)

In [7]:
# split data into input(X) and output(y) variables

In [8]:
X = data[:, 0:8]
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [9]:
y = data[:, 8]
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

# Define Keras Model

In [10]:
model = Sequential()
model.add(Dense(12, input_shape = (8, ), activation = 'relu'))
model.add(Dense(8, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [11]:
# relu is rectified linear unit activation function

In [14]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________
None


# Compile Kearas Model

In [12]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# 70% of the models are using optimizer as adam, adam is quick

# Fit Keras Model

Epoch: One pass through all of the rows in the training dataset


Batch: One or more samples considered by the model within an epoch before weights are updated

In [13]:
# One epoch comprises one or more batches,based on the chosen batch size
# the model is fit for many epochs

The training process will run for a fixed number of epochs (iterations) through the dataset that you must specify using the epochs argument. You must also set the number of dataset rows that are considered before the model weights are updated within each epoch, called the batch size, and set using the batch_size argument.

In [25]:
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)
...

Epoch 1/150
77/77 [==============================] - 1s 2ms/step - loss: 2.1319 - accuracy: 0.5326
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 1.1044 - accuracy: 0.6016
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8180 - accuracy: 0.5938
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7687 - accuracy: 0.6159
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7195 - accuracy: 0.6159
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7009 - accuracy: 0.6250
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7349 - accuracy: 0.6393
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7140 - accuracy: 0.6341
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6655 - accuracy: 0.6732
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6857 - accuracy: 0.6354
Epoch 11/

Ellipsis

# Evaluate Karas Model

In [26]:

...
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

24/24 [==============================] - 0s 2ms/step - loss: 0.5188 - accuracy: 0.7474
Accuracy: 74.74


# Summary - tie it all together

In [40]:
# first neural network with keras tutorial
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
# load the dataset
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
dataset = loadtxt(path, delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]
# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(8,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
model.fit(X, y, epochs=200, batch_size=10)
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/200
77/77 [==============================] - 1s 2ms/step - loss: 6.1663 - accuracy: 0.5365
Epoch 2/200
77/77 [==============================] - 0s 2ms/step - loss: 1.6815 - accuracy: 0.6120
Epoch 3/200
77/77 [==============================] - 0s 2ms/step - loss: 1.1361 - accuracy: 0.6120
Epoch 4/200
77/77 [==============================] - 0s 2ms/step - loss: 0.9656 - accuracy: 0.5990
Epoch 5/200
77/77 [==============================] - 0s 2ms/step - loss: 0.8833 - accuracy: 0.6016
Epoch 6/200
77/77 [==============================] - 0s 2ms/step - loss: 0.8488 - accuracy: 0.5807
Epoch 7/200
77/77 [==============================] - 0s 2ms/step - loss: 0.8029 - accuracy: 0.6003
Epoch 8/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7867 - accuracy: 0.5964
Epoch 9/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7527 - accuracy: 0.6146
Epoch 10/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7310 - accuracy: 0.6068
Epoch 11/

# Make Predictions

In [30]:
# make probability predictions with the model
predictions = model.predict(X)
# round predictions 
rounded = [round(x[0]) for x in predictions]

24/24 [==============================] - 0s 2ms/step


In [32]:

# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)

24/24 [==============================] - 0s 2ms/step


In [33]:
# summarize the first 5 cases
for i in range(5):
	print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))

[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] => 1 (expected 1)
[1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] => 0 (expected 0)
[8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] => 1 (expected 1)
[1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] => 0 (expected 0)
[0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] => 1 (expected 1)


# Full Summary of Keras Model

In [44]:
# first neural network with keras make predictions
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
# load the dataset
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
dataset = loadtxt(path, delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]
# define the keras model
model = Sequential()
model.add(Dense(22, input_shape=(8,), activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))
# fit the keras model on the dataset
model.fit(X, y, epochs=300, batch_size=10, verbose=0)
# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)
# summarize the first 5 cases
for i in range(5):
    print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))

24/24 [==============================] - 0s 2ms/step - loss: 8.1336 - accuracy: 0.4779
Accuracy: 47.79
24/24 [==============================] - 0s 1ms/step
[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] => 1 (expected 1)
[1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] => 0 (expected 0)
[8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] => 1 (expected 1)
[1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] => 0 (expected 0)
[0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] => 1 (expected 1)
