Kaggle Project: Vectors and Matrices


https://www.kaggle.com/code/jhossain/introduction-to-numpy-vectors-and-matrices/notebook

In [1]:
import numpy as np

In [2]:
vector_row = np.array([1,2,3])
print(vector_row)

[1 2 3]


In [3]:
vector_column = np.array([[1],[2],[3]])
print(vector_column)

[[1]
 [2]
 [3]]


In [4]:
mat1 = np.matrix('1,2,3,4;4,5,6,7;7,8,9,10')
print(mat1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [11]:
mat1_1 = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(mat1_1)
mat1_1.shape

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


(3, 4)

In [6]:
mat1_1 == mat1

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [8]:
mat2 = np.array([[1,2],[3,4],[4,6]])
print(mat2)

[[1 2]
 [3 4]
 [4 6]]


In [9]:
mat3 = np.matrix('1,2,3,4;4,5,6,7;7,8,9,10')
print(mat3)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [10]:
mat3.shape

(3, 4)

In [12]:
mat3.shape[0]

3

In [13]:
mat3.shape[1]

4

In [14]:
mat4 = np.matrix('1,2,3,4;4,5,6,7;7,8,9,10')
print(mat4)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [15]:
mat4.size


12

In [25]:
mat5 = np.matrix('1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10')
print(mat5)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [17]:
col_new = np.matrix('1,1,1')
print(col_new)

[[1 1 1]]


In [18]:
mat6 = np.insert(mat5, 0, col_new, axis=1)
#axis = 0 insert as row , axis=1 add like as column
print(mat6)

[[ 1  1  2  3  4]
 [ 1  4  5  6  7]
 [ 1  7  8  9 10]]


In [19]:
col_new_1 = np.array([[1],[1],[1]])
print(col_new_1)

[[1]
 [1]
 [1]]


In [20]:
mat6_1 = np.insert(mat5, 0, col_new_1, axis=1)
print(mat6_1)

[[ 1  1  1  1  2  3  4]
 [ 1  1  1  4  5  6  7]
 [ 1  1  1  7  8  9 10]]


In [22]:
mat6_2 = np.insert(mat5,2, col_new, axis=1)
print(mat6_2)

[[ 1  2  1  3  4]
 [ 4  5  1  6  7]
 [ 7  8  1  9 10]]


In [72]:
#mat6_3 = np.insert(mat5, 0, col_new, axis=0)
#print(mat6_3)

In [26]:
row_new = np.matrix('0, 0, 0, 0')
print(row_new)

[[0 0 0 0]]


In [27]:
mat7 = np.insert(mat5, 0, row_new, axis=0)
print(mat7)

[[ 0  0  0  0]
 [ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [30]:
mat_a = np.matrix('1, 2, 3, 4, 5; 5, 6, 7, 8, 9; 9, 10, 11, 12, 13')
print(mat_1)


[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [31]:
mat_a[1, 1] = 0
print(mat_a)


[[ 1  2  3  4  5]
 [ 5  0  7  8  9]
 [ 9 10 11 12 13]]


In [32]:
mat_a[1, 2] = 90
print(mat_a)

[[ 1  2  3  4  5]
 [ 5  0 90  8  9]
 [ 9 10 11 12 13]]


In [36]:
mat_a[1, :]


matrix([[ 5,  0, 90,  8,  9]])

In [37]:
mat_a[:, 2]


matrix([[ 3],
        [90],
        [11]])

In [38]:
mat_a[1, 2]

90

Matrix Operations

In [53]:
A = np.arange(0, 20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [54]:
B = np.arange(20, 40).reshape(5,4)
print(B)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [55]:
np.add(A, B)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [56]:
np.subtract(A, B)


array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

In [57]:
A_T = np.arange(0, 20).reshape(5,4)
print(A_T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [58]:
np.transpose(A_T)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [63]:
print(A);
print(B)
print(A.shape)
print(B.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
(5, 4)
(5, 4)


In [64]:
#np.dot(A, B)

#using dot function, needs to make sure columns in matrix A is equal to rows in matrix B

In [65]:
T = np.transpose(B)
print(T)

[[20 24 28 32 36]
 [21 25 29 33 37]
 [22 26 30 34 38]
 [23 27 31 35 39]]


In [66]:
np.dot(A,T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [67]:
np.matmul(A, T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [68]:
A @ T

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [73]:
np.multiply(A,B) # element-wise multiplication

array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525],
       [576, 629, 684, 741]])

In [71]:
np.divide(A, B)  # named division, it's actually inverse

array([[0.        , 0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923, 0.25925926],
       [0.28571429, 0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949]])